services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: tracezilla_shopify_connector_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - tracezilla_shopify_connector_postgres_data:/var/lib/postgresql/data

  docs:
    build:
      context: .
      dockerfile: docker/docs/Dockerfile
    working_dir: /docs
    volumes:
      - ./docs:/docs
      - tracezilla_shopify_connector_bundle:/usr/local/bundle
    ports:
      - "4000:4000"
    command: bundle exec jekyll serve --host 0.0.0.0

volumes:
  tracezilla_shopify_connector_postgres_data:
  tracezilla_shopify_connector_bundle: